# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix TTC')),
            ],
            options={
                'verbose_name': 'Tarif',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Evènement',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(choices=[('CB', 'Carte Bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement Bancaire')], max_length=3)),
            ],
            options={
                'verbose_name': 'Vente',
            },
        ),
        migrations.CreateModel(
            name='SellLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
            options={
                'verbose_name_plural': 'Lieux de vente',
                'verbose_name': 'Lieu de vente',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('classic', 'Classique'), ('yurplan', 'Yurplan'), ('va', 'Carte VA')], max_length=50)),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.Entry', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'Billet',
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_entry', to='ticketing.Ticket')),
            ],
            options={
                'verbose_name': 'Validation',
            },
        ),
        migrations.CreateModel(
            name='VALink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_id', models.IntegerField(verbose_name="Numéro d'adhérant")),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='va', to='ticketing.Ticket')),
            ],
            options={
                'verbose_name': 'Carte VA',
            },
        ),
        migrations.CreateModel(
            name='YurplanLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yurplan_id', models.CharField(max_length=70, verbose_name='Numéro de billet yurplan')),
                ('yurplan_event', models.IntegerField(verbose_name='Evènement Yurplan')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yurplan', to='ticketing.Ticket')),
            ],
            options={
                'verbose_name': 'Lien Yurplan',
            },
        ),
        migrations.AddField(
            model_name='sell',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='ticketing.SellLocation'),
        ),
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ticketing.Event', verbose_name='Evènement'),
        ),
    ]
