# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20170126_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sell',
        ),
        migrations.AddField(
            model_name='selllocation',
            name='events',
            field=models.ManyToManyField(related_name='locations', to='ticketing.Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='ticketing.SellLocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement Bancaire')], default='CB', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
