# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_auto_20170126_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('ESP', 'Espèces'), ('CHQ', 'Chèque'), ('VIR', 'Virement Bancaire')], default='CB', max_length=3, verbose_name='Méthode de paiement'),
        ),
    ]
