# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_auto_20170202_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_background',
            field=models.ImageField(blank=True, upload_to='', verbose_name="Fond d'image tickets"),
        ),
    ]
