# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_adapt_ticket_for_yurplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='yurplan_event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
