# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_event_yurplan_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='yurplan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
