# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_entry_yurplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='ticketing.SellLocation'),
        ),
    ]
