# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_auto_20170206_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='max_seats',
            field=models.IntegerField(default=1600, verbose_name='Nombre maximal de place'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.IntegerField(default=1600, verbose_name='Nombre maximal de place'),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_closing',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_opening',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='seats_goal',
            field=models.IntegerField(default=1600),
        ),
    ]
