# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0012_auto_20170206_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_days_count',
            field=models.IntegerField(default=13),
        ),
    ]
