# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0013_event_closed_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='selling_mode',
            field=models.CharField(choices=[('va_only', 'Que pour des membre VA'), ('no_va', 'Ne doit pas être VA'), ('whatever', "Qu'importe")], default='whatever', max_length=20),
        ),
    ]
